# Generated by Django 6.0 on 2026-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
