# Generated by Django 6.0 on 2026-04-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_userprogress_current_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='updated_at',
            new_name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='weighted_score',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_viewed_lesson',
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Time taken in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_weeks',
            field=models.JSONField(default=list, help_text='List of completed week numbers'),
        ),
        migrations.AddField(
            model_name='week',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='week',
            name='project_requirements',
            field=models.TextField(blank=True, help_text='Requirements in markdown format'),
        ),
        migrations.AddField(
            model_name='week',
            name='project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(help_text='Number of correct answers'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Why this is the correct answer')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of question in quiz')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.question')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizChoice',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
