# Generated by Django 6.0 on 2026-03-21 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='skilltopic',
            options={'ordering': ['week__number', 'order']},
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='content',
            field=models.TextField(default='', help_text='Main lesson content (HTML)'),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='duration',
            field=models.CharField(default='15 minutes', max_length=50),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skilltopic',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML Content'), ('markdown', 'Markdown'), ('structured', 'Structured JSON')], default='html', max_length=20),
        ),
        migrations.AlterField(
            model_name='skilltopic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilltopic',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dashboard.skillweek'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltopic',
            unique_together={('week', 'order')},
        ),
        migrations.CreateModel(
            name='TopicCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.skilltopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_topics', through='dashboard.TopicCompletion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skilltopic',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='skilltopic',
            name='requires_mentor',
        ),
        migrations.RemoveField(
            model_name='skilltopic',
            name='skill',
        ),
    ]
