# Generated by Django 6.0 on 2026-03-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_skillweek_alter_skilltopic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson_completed', 'Lesson Completed'), ('quiz_completed', 'Quiz Completed'), ('project_submitted', 'Project Submitted'), ('project_approved', 'Project Approved'), ('project_rejected', 'Project Rejected'), ('badge_earned', 'Badge Earned'), ('discussion_posted', 'Discussion Posted'), ('discussion_reply', 'Discussion Reply'), ('course_enrolled', 'Course Enrolled'), ('course_completed', 'Course Completed'), ('streak_milestone', 'Streak Milestone'), ('points_milestone', 'Points Milestone')], max_length=50)),
                ('title', models.CharField(help_text='Main heading shown in activity feed', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the activity')),
                ('related_topic_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('related_discussion_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Hide sensitive activities if needed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_7f2c17_idx'), models.Index(fields=['activity_type'], name='dashboard_a_activit_3b6f87_idx')],
            },
        ),
    ]
