# Generated by Django 6.0 on 2026-02-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('badge_type', models.CharField(choices=[('streak', 'Streak Achievement'), ('reviewer', 'Top Reviewer'), ('projects', 'Project Milestone'), ('community', 'Community Contributor'), ('mentor', 'Mentor Excellence')], max_length=30)),
                ('awarded_to', models.ManyToManyField(blank=True, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('cert_type', models.CharField(choices=[('Full Course', 'Full Course'), ('Milestone', 'Milestone'), ('Specialization', 'Specialization')], default='Full Course', max_length=50)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Revoked', 'Revoked')], default='Verified', max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('projects_validated', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
