# Generated by Django 6.0 on 2026-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_discussionthread_discussionreply_projectfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
