# Generated by Django 6.0 on 2026-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_peerprojectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerprojectreview',
            name='documentation_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerprojectreview',
            name='functionality_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerprojectreview',
            name='structure_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerprojectreview',
            name='syntax_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='documentation_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='functionality_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='structure_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='syntax_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
