# Generated by Django 6.0 on 2026-04-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_peerprojectreview_documentation_score_and_more'),
        ('courses', '0002_enrollment_unique_active_enrollment_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityproject',
            name='submitted_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_projects', to='courses.course'),
        ),
    ]
