# Generated by Django 6.0 on 2026-04-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_communityproject_submitted_course'),
        ('courses', '0003_cohort_enrollment_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityproject',
            name='submitted_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_projects', to='courses.cohort'),
        ),
    ]
